### PR TITLE
[Backport 1.x] Register new routes via SDK as named routes (#827) and Makes route prefix setting routeNamePrefix optional #868

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Manually Backports #827 & #868

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dbwiddis** [comment]
Looks like the Integ Test fix from original doesn't work on backport....

**Comment by DarshitChanpura** [comment]
I've created the backport for the integ test fix: https://github.com/opensearch-project/OpenSearch/pull/8588

**Review by dbwiddis — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

**Comment by joshpalis** [comment]
Before we merge this backport : https://github.com/opensearch-project/opensearch-sdk-java/pull/827#issuecomment-1629588184

**Review by dbwiddis — CHANGES_REQUESTED** [review]
See https://github.com/opensearch-project/opensearch-sdk-java/pull/827#issuecomment-1629622060

**Comment by DarshitChanpura** [comment]
> See [#827 (comment)](https://github.com/opensearch-project/opensearch-sdk-java/pull/827#issuecomment-1629622060)

Addressed in this PR. And raised a separate PR to main: https://github.com/opensearch-project/opensearch-sdk-java/pull/868

**Comment by joshpalis** [comment]
@DarshitChanpura #868 has been merged

**Review by joshpalis — APPROVED** [review]

**Review by dbwiddis — APPROVED** [review]

**Pull request merged**
