### PR TITLE
Add copyright line to license headers

### LINKED ISSUE #194: License Header Update
### Is your feature request related to a problem?

Our license header doesn't include the Copyright lines as indicated in https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#java

I blame whoever submitted #51 for not doing it right. :-)

Also there's a stray `license` directory with some old netty licenses in it that needs to be removed.

### What solution would you like?

Update the license header per above link.  It's a simple template change in Spotless, and from there we have two choice:
 - Accept the pain of a one-time rewrite of all headers
 - Use `ratchetFrom` functionality to only apply spotless to changed files.   Since all files in the repo are already compliant, this should work just fine, and will update the headers on files as we change them over time:
```
spotless {
  ratchetFrom 'origin/main' // only format files which have changed since origin/main
```

### What alternatives have you considered?
Leaving the license as-is.  Copyright statements aren't technically required. But we should be consistent!

### Do you have any additional context?

We should also discuss whether we want a blank line between the license header and `package` declaration.

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

Adds copyright line to conform license header to format per https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#java

### Issues Resolved
Fixes #194 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dbwiddis** [comment]
I should probably make changes to the `workflow_run` trickery from #193.  While the gradle check is correctly triggered,
 - it does not show up in the checks associated with this PR
 - the pull_request and pull_request_target triggers are redundant and it runs twice.

Screen Shot 2022-10-17 at 12 08 41 PM

**Comment by peternied** [comment]
You can use a smaller license header, while you are doing so I'd recommend the tiny one [1] [2]

```
/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
```

[1] https://github.com/opensearch-project/OpenSearch/pull/4657
[2] https://github.com/opensearch-project/alerting/issues/136#issuecomment-966657180

**Comment by dbwiddis** [comment]
Flipping this to draft to discuss @peternied comment. I went searching everywhere for that official guidance, and it's very confusing.  

Why is the contributing document not up to date with the guidance in [this comment](https://github.com/opensearch-project/alerting/issues/136#issuecomment-966657180) from @AMoo-Miki?  

What is the scope of "like this one" mentioned in that comment?

Where is the official guidance if not at the CONTRIBUTING link cited above?

**Comment by dbwiddis** [comment]
I believe the guidance linked by @peternied is outdated as of https://github.com/opensearch-project/.github/pull/76 which updated to the version I'm using.

I filed an issue to request final clarification:  https://github.com/opensearch-project/.github/issues/98

**Review by saratvemulapalli — APPROVED** [review]

**Review by joshpalis — APPROVED** [review]
Thanks Dan for taking care of this!

**Pull request merged**
