### PR TITLE
Renaming to match changes on OpenSearch repo

### PR DESCRIPTION
**Pull request by ryanbogan**
Signed-off-by: Ryan Bogan <rbogan@amazon.com>

### Description
Renames two classes to reflect the changes in OpenSearch repo

Main PR with reasoning for renaming: https://github.com/opensearch-project/OpenSearch/pull/5347/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — CHANGES_REQUESTED** [review]
I'm missing what is changing in the svg (which still says orchestrator on it).

**Comment by ryanbogan** [comment]
Should be fixed now @dbwiddis

**Comment by dbwiddis** [comment]
> Should be fixed now @dbwiddis

A little formatting oddness. Looks like you manually edited the text in the svg file? :) 

I'll send you the text file so you can edit it and get the benefit of formatting.

**Comment by owaiskazi19** [comment]
@ryanbogan Can you run `./gradlew spotlessApply` as build is failing. Also, did we check if renaming needs to be done for `feature/extensions` of AD?

**Review by dbwiddis — APPROVED** [review]
LGTM. Can you add a link in the first comment to the corresponding PR in the main project?

I assume that other link explains the reasoning for the name change?

**Pull request merged**
