### PR TITLE
Switch to more reliable OpenSearch Lucene snapshot location

### PR DESCRIPTION
**Pull request by peternied**
### Description
Switch to more reliable OpenSearch Lucene snapshot location

### Issues Resolved
- Related https://github.com/opensearch-project/opensearch-build/issues/3874
- Related https://github.com/opensearch-project/OpenSearch/pull/11728

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@dbwiddis Could you take a look?

**Review by saratvemulapalli — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

**Comment by peternied** [comment]
@owaiskazi19 @saratvemulapalli  Looks like there is an unrelated build break can you let me know how this should move forward?
```
/home/runner/work/opensearch-sdk-java/opensearch-sdk-java/src/test/java/org/opensearch/sdk/TestExtensionInterfaces.java:175: error: constructor Parameters in class Parameters cannot be applied to given types;
        Processor.Parameters parameters = new Processor.Parameters(null, null, null, null, null, null, null, null, null);
                                          ^
```

**Comment by owaiskazi19** [comment]
> @owaiskazi19 @saratvemulapalli Looks like there is an unrelated build break can you let me know how this should move forward?
> 
Should be fixed by https://github.com/opensearch-project/opensearch-sdk-java/pull/979.

**Comment by peternied** [comment]
@owaiskazi19 Looks like there are still issues with the PR checks, I've created a issue:
- https://github.com/opensearch-project/opensearch-sdk-java/issues/981

**Comment by saratvemulapalli** [comment]
@peternied here is the fix https://github.com/opensearch-project/opensearch-sdk-java/pull/982
Please rebase after the changes are merged.

**Pull request merged**
