### PR TITLE
Add setup for GitHub pages

### PR DESCRIPTION
**Pull request by kolchfa-aws**
### Description
Sets up the necessary config and styling files for the GitHub pages theme.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ryanbogan — APPROVED** [review]

**Comment by dbwiddis** [comment]
LGTM, holding off on merging until https://github.com/opensearch-project/OpenSearch/pull/8588 is merged, so that backport works more smoothly.

**Comment by kolchfa-aws** [comment]
Sure, but I don't think we need to backport this one though. It should work off the main branch only.

**Comment by owaiskazi19** [comment]
> Sure, but I don't think we need to backport this one though. It should work off the main branch only.

@kolchfa-aws we will be releasing SDK in 2.9 from 1.x branch. I think the branch should be updated with the latest document changes. @dbwiddis IMO we should backport this to 1.x.

**Comment by dbwiddis** [comment]
> @dbwiddis IMO we should backport this to 1.x.

These docs live on a single branch (I'm not sure exactly which repo, but a `gh-pages` branch usually.) They won't get published from another branch.  Probably doesn't hurt to backport but will never be read under current config.

**Pull request merged**
