### PR TITLE
[Backport 1.x] Initial Hello World Extension integration test

### PR DESCRIPTION
**Pull request by ryanbogan**
### Description
Sets `./gradle check` to depend on `integTest` task. Adds an integration test to send an initialization request from OpenSearch to the hello world extension.

Additionally this PR removes the TransportCommunicationIT test class as this will need to be redone.

Backport of https://github.com/opensearch-project/opensearch-sdk-java/pull/874

### Issues Resolved
https://github.com/opensearch-project/opensearch-sdk-java/issues/867

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ryanbogan** [comment]
@reta I believe this is failing due to a gradle update, but I can't figure out how to fix it.  Any ideas?

**Comment by dbwiddis** [comment]
I first saw this symptom in the Gradle 8.2 version bump (https://github.com/opensearch-project/opensearch-sdk-java/pull/855).  
```
org.gradle.api.GradleException: Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0
        at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.displayDeprecationIfSameMessageNotDisplayedBefore(LoggingDeprecatedFeatureHandler.java:90)
        at org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler.featureUsed(LoggingDeprecatedFeatureHandler.java:75)
        at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:347)
        at org.gradle.internal.deprecation.DeprecationLogger.nagUserWith(DeprecationLogger.java:246)
        at org.gradle.internal.deprecation.DeprecationMessageBuilder$WithDocumentation.nagUser(DeprecationMessageBuilder.java:130)
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
```

I know there's a deprecation warning which is fine but it seems it's throwing an uncaught exception failing builds.   This is supposed to be a 9.0 warning, not "we're no longer backwards compatible starting with 8.2."

It seems to be transient, sometimes builds work.

I've searched for bugs at Gradle and not seen any.

I think options include:
 - downgrade to Gradle 8.1
 - fix OpenSearch Gradle Plugin to remove the deprecated features

**Comment by reta** [comment]
@ryanbogan @dbwiddis  we've never updated Gradle on OpenSearch `1.x` because update to 8.x was breaking things (like this one, so if we would, we would have broken all plugins) :(

**Comment by dbwiddis** [comment]
@reta our 1.x is OpenSearch 2.x.

**Comment by reta** [comment]
> @reta our 1.x is OpenSearch 2.x

Oh, sorry about that, I will take a look shortly

**Comment by reta** [comment]
@ryanbogan @dbwiddis please use 2.10.0-SNAPSHOT, the  Gradle 8.2.1 was not merged into 2.9

```
        opensearch_version = System.getProperty("opensearch.version", "2.10.0-SNAPSHOT")

```

**Comment by ryanbogan** [comment]
Seems like we need to downgrade the gradle version for the SDK for 2.9 then

**Comment by ryanbogan** [comment]
PR here: https://github.com/opensearch-project/opensearch-sdk-java/pull/884

**Review by owaiskazi19 — APPROVED** [review]

**Pull request merged**
