### PR TITLE
[Backport 1.x] Updated dev guide with the correct GET route.

### PR DESCRIPTION
**Pull request by dbwiddis**
Backport ee55c5d36854e7b4d8c43afc4dc6b0c0212ccf92 from https://github.com/opensearch-project/opensearch-sdk-java/pull/944

### CODE REVIEW

**Comment by dblock** [comment]
Thanks for doing this for me @dbwiddis

**Review by owaiskazi19 — APPROVED** [review]

**Comment by dblock** [comment]
@dbwiddis care to amend with DCO?

**Comment by dbwiddis** [comment]
> @dbwiddis care to amend with DCO?

DCO failure is yours I think?  This is just a cherry-pick.

> Commit sha: [94b380a](https://github.com/opensearch-project/opensearch-sdk-java/pull/948/commits/94b380a553acb1c9110c640da1895b69f3ce8f77), Author: Daniel (dB.) Doubrovkine, Committer: Daniel Widdis; Expected "Daniel (dB.) Doubrovkine [dblock@amazon.com](mailto:dblock@amazon.com)", but got "dblock [dblock@amazon.com](mailto:dblock@amazon.com)".

How do we fix that?

**Comment by dbwiddis** [comment]
> How do we fix that?

I amended to edit your DCO to match your committer name. Hope that's ok with you as the original signer!

**Pull request merged**
