### PR TITLE
[Backport 1.x] Adds getExecutorBuilders and indexNameExpressionResolver to extensionsRunner

### PR DESCRIPTION
**Pull request by joshpalis**
### Description
Backport of https://github.com/opensearch-project/opensearch-sdk-java/pull/627

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by joshpalis** [comment]
```
> Task :compileJava
/home/runner/work/opensearch-sdk-java/opensearch-sdk-java/src/main/java/org/opensearch/sdk/action/SDKActionModule.java:[24](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4567197489/jobs/8060697418#step:4:25): error: cannot find symbol
import org.opensearch.extensions.RegisterTransportActionsRequest;
                                ^
  symbol:   class RegisterTransportActionsRequest
  location: package org.opensearch.extensions
/home/runner/work/opensearch-sdk-java/opensearch-sdk-java/src/main/java/org/opensearch/sdk/action/SDKActionModule.java:1[26](https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/4567197489/jobs/8060697418#step:4:27): error: cannot find symbol
                new RegisterTransportActionsRequest(uniqueId, getActions().keySet()),
                    ^
  symbol:   class RegisterTransportActionsRequest
  location: class SDKActionModule
Note: /home/runner/work/opensearch-sdk-java/opensearch-sdk-java/src/main/java/org/opensearch/sdk/SDKClient.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by owaiskazi19** [comment]
> Failing class was added in 2.x in [opensearch-project/OpenSearch#6829](https://github.com/opensearch-project/OpenSearch/pull/6829) merged 2 days ago. Are snapshots being published?

No: https://github.com/opensearch-project/opensearch-sdk-java/actions/workflows/publish-snapshots.yml

**Comment by dbwiddis** [comment]
Looks like this 1.x branch has been failing since the xContent PR merge #618

**Comment by dbwiddis** [comment]
This diff looks suspicious with different matching imports (missing the parser on the new version in SDKNamedXContentRegistry)
```diff
- import org.opensearch.common.xcontent.NamedXContentRegistry;
- import org.opensearch.common.xcontent.XContentParser;
- import org.opensearch.common.xcontent.NamedXContentRegistry.Entry;
+ import org.opensearch.core.xcontent.NamedXContentRegistry;
+ import org.opensearch.core.xcontent.NamedXContentRegistry.Entry;
```

**Comment by dbwiddis** [comment]
Theory (untested):

Add an import to `SDKNamedXContentRegistry` to `import org.opensearch.core.xcontent.XContentParser;`

**Comment by joshpalis** [comment]
@dbwiddis still failing due to stale SDK 1.0.0 snapshots here : https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/sdk/opensearch-sdk-java/. It hasnt been updated since 03/27/2023

**Comment by joshpalis** [comment]
@dbwiddis @owaiskazi19  looks like the package for `RegisterTransportActions` on [OpenSearch 2.x](https://github.com/opensearch-project/OpenSearch/blob/0c32a58a7d383b899c34ee589f40deee1c947259/server/src/main/java/org/opensearch/extensions/action/RegisterTransportActionsRequest.java#L9) is `org.opensearch.extensions.action` not `org.opensearch.extensions`.

**Comment by owaiskazi19** [comment]
> @dbwiddis still failing due to stale snapshots Ill re-run the checks after it is updated

@joshpalis snapshots are failing because of the above compile Java issue I posted

**Review by owaiskazi19 — APPROVED** [review]

**Pull request merged**
