### PR TITLE
Updated repository location on jenkins

### PR DESCRIPTION
**Pull request by owaiskazi19**
### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
Could you explain why these changes are required?

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
> Could you explain why these changes are required?

The path mentioned was incorrect. See the failed workflow here https://build.ci.opensearch.org/view/Release/job/opensearch-sdk-java-release/2/console

**Review by joshpalis — APPROVED** [review]

**Comment by joshpalis** [comment]
Failing due to : 
```
/home/runner/work/opensearch-sdk-java/opensearch-sdk-java/src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestHelloAction.java:103: error: cannot find symbol
            XContentType contentType = request.getXContentType();
```

**Comment by owaiskazi19** [comment]
The build failure are for the imports, which is not related to this PR.

**Pull request merged**
