### PR TITLE
Added untriaged issue workflow.

### PR DESCRIPTION
**Pull request by dblock**
Coming from https://github.com/opensearch-project/.github/issues/133, create a GitHub workflow for labelling untriaged issues. Please ensure that an untriaged label with color  exists before merging.

### CODE REVIEW

**Review by dbwiddis — COMMENTED** [review]
We already have an untriaged label that is added to most new issues during the creation process.  This is part of the templates from .github repo which include the default labels ([bug, untriaged for bug reports](https://github.com/opensearch-project/.github/blob/main/.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md) and [enhancment, untriaged for feature requests](https://github.com/opensearch-project/.github/blob/main/.github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md).  It's not included for proposals (but could be added at .github) or the "blank issue" that users have to go out of their way to click.

Many times maintainers add the issues themselves and intentionally remove the untriaged label to prevent noise on the issue (and to more easily identify untriaged user issues submitted via bug or feature templates).

**Comment by dbwiddis** [comment]
FIxed the spotless errors. Not sure what it was but probably windows CRLF.

I'd prefer to remove "opened" from this PR to allow untriaged on reopened/transferred, but I think the bug/feature workflows are sufficient for us, so I'm not going to approve it myself. However, if two other maintainers want to approve this as is, I won't yell.

**Review by dbwiddis — APPROVED** [review]
So I spent far more time than I should have investigating a way to read CODEOWNERS and conditionally apply this label, but [at some point I broke this matrix](https://xkcd.com/1205/).

So I'll just learn methods to mass-remove tags quickly when I want to. :)

**Review by ryanbogan — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

**Comment by dblock** [comment]
Sorry about the CR/LFs, I copied another workflow.

**Comment by dbwiddis** [comment]
Insert smack talk about Windows vs. *nix here.

**Pull request merged**
